server:
  port : 9090
  
hie:
    username: lims
    password: extegIbANGLUmedIpEnD
    shared-health-record:
        url: http://197.221.242.150:10343/SHR/fhir/
    client-registry:
        url: http://197.221.242.150:10343/CR/fhir/
        
        
        
            
        
#https://impilo-openhimcore.mohcc.gov.zw/SHR/fhir/
#url:http://197.221.242.150:10343/lims-fhir/
