server:
  port : 9090
  
openhie:
    shared-health-record:
        url: https://impilo-openhimcore.mohcc.gov.zw/SHR/fhir/
        username: lims
        password: extegIbANGLUmedIpEnD
        
        
            
        
#https://impilo-openhimcore.mohcc.gov.zw/SHR/fhir/
#url:http://197.221.242.150:10343/lims-fhir/
