server:
  port : 9090
  
openhie:
    shared-health-record:
        url: http://localhost:8090/fhir/
        username: mohcc-lims
        password: MiMLS$421^KrL!
        
        
            
        
#url:http://197.221.242.150:10343/lims-fhir/
