server:
  port : 9090
  
hie:
    username: lims
    password: my-lims
    shared-health-record:
        url: https://core-openhim-zhie.mohcc.gov.zw/SHR/fhir/
    client-registry:
        url: https://core-openhim-zhie.mohcc.gov.zw/CR/fhir/
        
        
        
            
        
#https://impilo-openhimcore.mohcc.gov.zw/SHR/fhir/
#url:http://197.221.242.150:10343/lims-fhir/
